
import App.NewClass;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MUVUNYI Iddi
 */
public class managerPanel extends javax.swing.JFrame {

   
    /**
     * Creates new form managerPanel
     */
    
   
    public managerPanel() {
        initComponents();
        showDate();
        fetchData_Customer();
        generateId();
        generateDocId();
        fetchData_Document();
        Police_Station();
        Documents_Type();
        fetch_Doc_types();
        
        
        employeeName.setText(String.valueOf(NewClass.emplnames).toString());
         seticon();
    }
    
    
     void showDate(){
      Date d = new Date();
      SimpleDateFormat s =new SimpleDateFormat("d-MM-Y");
      time.setText(s.format(d));
  }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popp = new javax.swing.JPopupMenu();
        reports = new javax.swing.JMenuItem();
        edits = new javax.swing.JMenuItem();
        jPop = new javax.swing.JPopupMenu();
        stats = new javax.swing.JMenuItem();
        view = new javax.swing.JMenuItem();
        bg2 = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_create = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_check = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTbl = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        search3 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        create = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        field1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        field4 = new javax.swing.JTextField();
        field5 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        field13 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        btn_female = new javax.swing.JRadioButton();
        btn_male = new javax.swing.JRadioButton();
        field2 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        sign = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        nid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        stmt = new javax.swing.JTextArea();
        edit = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        no = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        docowner = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        docno = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        docissue = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        doctype = new javax.swing.JComboBox<>();
        location = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        info2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        check = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        docTbl = new javax.swing.JTable();
        search2 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        reveal = new javax.swing.JLabel();
        employeeName = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        reports.setText("Report Details");
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });
        popp.add(reports);

        edits.setText("Edit Crime");
        edits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editsActionPerformed(evt);
            }
        });
        popp.add(edits);

        stats.setText("Mark as Collected");
        stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsActionPerformed(evt);
            }
        });
        jPop.add(stats);

        view.setText("Full Details");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPop.add(view);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 60));

        bg2.setBackground(new java.awt.Color(255, 255, 255));
        bg2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top.setBackground(new java.awt.Color(183, 190, 98));
        top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("POLICE STATION");
        top.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 36));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Police_Badge_52px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        top.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 50));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        top.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 80, 10));

        btn_home.setBackground(new java.awt.Color(115, 167, 179));
        btn_home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(183, 190, 98), 1, true));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Home_18px.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(115, 167, 179));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Home");

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        top.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 100, 40));

        btn_create.setBackground(new java.awt.Color(64, 112, 130));
        btn_create.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(183, 190, 98), 1, true));
        btn_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_createMouseClicked(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Add_User_Male_18px.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Crime Reports");

        javax.swing.GroupLayout btn_createLayout = new javax.swing.GroupLayout(btn_create);
        btn_create.setLayout(btn_createLayout);
        btn_createLayout.setHorizontalGroup(
            btn_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_createLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_createLayout.setVerticalGroup(
            btn_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        top.add(btn_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 130, 40));

        btn_check.setBackground(new java.awt.Color(64, 112, 130));
        btn_check.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(183, 190, 98), 1, true));
        btn_check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_checkMouseClicked(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Check_All_18px_2.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Docs Status");

        javax.swing.GroupLayout btn_checkLayout = new javax.swing.GroupLayout(btn_check);
        btn_check.setLayout(btn_checkLayout);
        btn_checkLayout.setHorizontalGroup(
            btn_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_checkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_checkLayout.setVerticalGroup(
            btn_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        top.add(btn_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 120, 40));

        btn_edit.setBackground(new java.awt.Color(64, 112, 130));
        btn_edit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(183, 190, 98), 1, true));
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Edit_File_18px.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Documents");

        javax.swing.GroupLayout btn_editLayout = new javax.swing.GroupLayout(btn_edit);
        btn_edit.setLayout(btn_editLayout);
        btn_editLayout.setHorizontalGroup(
            btn_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_editLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        btn_editLayout.setVerticalGroup(
            btn_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        top.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 130, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        top.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 59, 480, 30));

        bg2.add(top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 80));

        main.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(243, 243, 252));
        home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 175, 192), 1, true));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportTbl.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        reportTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Names", "Gender", "National Id", "Occupation", "Phone No", "Address", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reportTbl.setGridColor(new java.awt.Color(255, 255, 255));
        reportTbl.setRowHeight(25);
        reportTbl.setSelectionBackground(new java.awt.Color(186, 153, 66));
        reportTbl.getTableHeader().setReorderingAllowed(false);
        reportTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                reportTblMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(reportTbl);
        if (reportTbl.getColumnModel().getColumnCount() > 0) {
            reportTbl.getColumnModel().getColumn(0).setPreferredWidth(1);
            reportTbl.getColumnModel().getColumn(2).setPreferredWidth(8);
        }

        home.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 830, 220));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(60, 99, 130));
        jLabel15.setText("Reported Crimes");
        home.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, 27));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_People_32px.png"))); // NOI18N
        home.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 30, 27));

        jPanel1.setBackground(new java.awt.Color(243, 243, 252));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 112, 130)));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(60, 99, 130));
        jLabel3.setText("Messages");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        home.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 170, 30));

        jPanel2.setBackground(new java.awt.Color(64, 112, 130));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 112, 130), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        home.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 170, 10));

        search3.setBackground(new java.awt.Color(240, 240, 240));
        search3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 175, 192), 1, true));
        search3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search3KeyReleased(evt);
            }
        });
        home.add(search3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 130, 27));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Search_23px.png"))); // NOI18N
        home.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jButton2.setText("Case Results");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        home.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 130, 30));

        main.add(home, "card2");

        create.setBackground(new java.awt.Color(243, 243, 252));
        create.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 175, 192), 1, true));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 175, 192), 1, true));
        jPanel5.setForeground(new java.awt.Color(149, 175, 192));

        jLabel41.setText(" Id");

        jLabel42.setText(" Names");

        jButton6.setBackground(new java.awt.Color(34, 131, 77));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Enter_17px_1.png"))); // NOI18N
        jButton6.setText("Save");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel45.setText("Address");

        field5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field5KeyTyped(evt);
            }
        });

        jLabel46.setText("Phone No");

        field13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field13KeyTyped(evt);
            }
        });

        jLabel49.setText("Gender");

        jLabel51.setText("Occupation");

        btn_female.setText("Female");
        btn_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_femaleActionPerformed(evt);
            }
        });

        btn_male.setText("Male");
        btn_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maleActionPerformed(evt);
            }
        });

        field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field2ActionPerformed(evt);
            }
        });
        field2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field2KeyTyped(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sign, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sign, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        jLabel52.setText("Statement");

        jLabel53.setText("Signature");

        jPanel12.setBackground(new java.awt.Color(39, 90, 105));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CRIME REPORT FORM");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        nid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nidKeyTyped(evt);
            }
        });

        jLabel12.setText("NID");

        stmt.setColumns(20);
        stmt.setRows(5);
        jScrollPane3.setViewportView(stmt);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel41))
                                            .addComponent(jLabel42))
                                        .addGap(14, 14, 14)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(field1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(field2)
                                    .addComponent(nid)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(14, 14, 14)
                                .addComponent(btn_female)
                                .addGap(55, 55, 55)
                                .addComponent(btn_male)))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel46))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addGap(10, 10, 10)
                                .addComponent(field13, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 608, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53))
                .addGap(63, 63, 63))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(field4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(nid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(btn_female)
                            .addComponent(btn_male)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );

        javax.swing.GroupLayout createLayout = new javax.swing.GroupLayout(create);
        create.setLayout(createLayout);
        createLayout.setHorizontalGroup(
            createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        createLayout.setVerticalGroup(
            createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        main.add(create, "card3");

        edit.setBackground(new java.awt.Color(243, 243, 252));
        edit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 175, 192), 1, true));
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(115, 167, 179), 1, true));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        jPanel13.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 150, -1));

        jLabel4.setText("No");
        jPanel13.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 20));

        jLabel8.setText("Document Owner");
        jPanel13.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));

        docowner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                docownerKeyTyped(evt);
            }
        });
        jPanel13.add(docowner, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 150, -1));

        jLabel14.setText("Doc Number");
        jPanel13.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, 20));

        docno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                docnoKeyTyped(evt);
            }
        });
        jPanel13.add(docno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 150, -1));

        jLabel21.setText("Place of Issue");
        jPanel13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, 20));
        jPanel13.add(docissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 150, -1));

        jLabel22.setText("Police Station");
        jPanel13.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 20));

        jButton1.setBackground(new java.awt.Color(34, 131, 77));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Enter_17px_1.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 140, 40));

        jPanel13.add(doctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, -1));

        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });
        jPanel13.add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 150, -1));

        jLabel23.setText("Document Type");
        jPanel13.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        edit.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 134, 640, 287));

        jPanel9.setBackground(new java.awt.Color(115, 167, 179));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(115, 167, 179), 1, true));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ADD LOST DOCUMENT ");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 140, 30));

        edit.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 63, 640, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        info2.setBackground(new java.awt.Color(115, 167, 179));
        info2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                info2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                info2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                info2MousePressed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("New Document Type");

        javax.swing.GroupLayout info2Layout = new javax.swing.GroupLayout(info2);
        info2.setLayout(info2Layout);
        info2Layout.setHorizontalGroup(
            info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        info2Layout.setVerticalGroup(
            info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(info2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(info2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        edit.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 620, 30));

        main.add(edit, "card4");

        check.setBackground(new java.awt.Color(243, 243, 252));
        check.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 175, 192), 1, true));
        check.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docTbl.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        docTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Names", "Document Type", "Document Number", "Place of Issue", "Police Station", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        docTbl.setGridColor(new java.awt.Color(255, 255, 255));
        docTbl.setRowHeight(25);
        docTbl.setSelectionBackground(new java.awt.Color(202, 166, 101));
        docTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                docTblMouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(docTbl);
        if (docTbl.getColumnModel().getColumnCount() > 0) {
            docTbl.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        check.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 810, 220));

        search2.setBackground(new java.awt.Color(243, 243, 252));
        search2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 175, 192), 1, true));
        search2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search2KeyReleased(evt);
            }
        });
        check.add(search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 140, 30));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Search_23px.png"))); // NOI18N
        check.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jPanel8.setBackground(new java.awt.Color(115, 167, 179));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(115, 167, 179), 1, true));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status Of Lost Document");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel10)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        check.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 350, 20));

        main.add(check, "card5");

        bg2.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 850, 460));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_User_21px_1.png"))); // NOI18N
        bg2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 20, 30));

        reveal.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        reveal.setForeground(new java.awt.Color(60, 99, 130));
        reveal.setText("Officer");
        bg2.add(reveal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 31));

        employeeName.setBackground(new java.awt.Color(248, 249, 255));
        employeeName.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        employeeName.setForeground(new java.awt.Color(0, 151, 144));
        bg2.add(employeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, 31));

        time.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        time.setForeground(new java.awt.Color(60, 99, 130));
        bg2.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 70, 20));

        jLabel30.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(60, 99, 130));
        jLabel30.setText("Date :");
        bg2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 40, 20));

        jLabel28.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(149, 175, 192));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Calendar_22px_1.png"))); // NOI18N
        bg2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        // TODO add your handling code here:
        setcolor(btn_home);
        resetcolor(btn_create);
        resetcolor(btn_edit);
        resetcolor(btn_check);

        // to switch pages by just a click
        main.removeAll();
        main.repaint();
        main.revalidate();

        main.add(home);
        main.repaint();
        main.revalidate();
        fetchData_Customer();

    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_createMouseClicked
        // TODO add your handling code here:
        setcolor(btn_create);
        resetcolor(btn_home);
        resetcolor(btn_edit);
        resetcolor(btn_check);

        // to switch pages by just a click
        main.removeAll();
        main.repaint();
        main.revalidate();

        main.add(create);
        main.repaint();
        main.revalidate();
        field1.setText("");
        field2.setText("");
        stmt.setText("");
        field4.setText("");
        field5.setText("");
        field13.setText("");
        nid.setText("");
        field1.requestFocus();
        btn_female.setSelected(false);
        btn_male.setSelected(false);
        generateId();
    }//GEN-LAST:event_btn_createMouseClicked

    private void btn_checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_checkMouseClicked
        // TODO add your handling code here:
        setcolor(btn_check);
        resetcolor(btn_create);
        resetcolor(btn_edit);
        resetcolor(btn_home);

        // to switch pages by just a click
        main.removeAll();
        main.repaint();
        main.revalidate();

        main.add(check);
        main.repaint();
        main.revalidate();
        
       
    }//GEN-LAST:event_btn_checkMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        // TODO add your handling code here:
        setcolor(btn_edit);
        resetcolor(btn_create);
        resetcolor(btn_check);
        resetcolor(btn_home);

        // to switch pages by just a click
        main.removeAll();
        main.repaint();
        main.revalidate();

        main.add(edit);
        main.repaint();
        main.revalidate();
        
        generateDocId();
        fetch_Doc_types();
       
    }//GEN-LAST:event_btn_editMouseClicked

    private void search3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search3KeyReleased
        // TODO add your handling code here:
         DefaultTableModel table = (DefaultTableModel)reportTbl.getModel();
        String search = search3.getText();
        TableRowSorter<DefaultTableModel>tr = new TableRowSorter<DefaultTableModel>(table);
       reportTbl.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_search3KeyReleased

    
    
    private void btn_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maleActionPerformed
        // TODO add your handling code here:
        gender="M";
        if(btn_male.isSelected()){
            btn_female.setSelected(false);
        }
    }//GEN-LAST:event_btn_maleActionPerformed

    private void btn_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_femaleActionPerformed
        // TODO add your handling code here:
        gender="F";
        if(btn_female.isSelected()){
            btn_male.setSelected(false);
        }
    }//GEN-LAST:event_btn_femaleActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //validating form fields
        if(field1.getText().trim().isEmpty() && field2.getText().trim().isEmpty() && field4.getText().trim().isEmpty() && field5.getText().trim().isEmpty() && field13.getText().trim().isEmpty() && nid.getText().trim().isEmpty() && ! btn_female.isSelected()&& ! btn_male.isSelected()&& stmt.getText().trim().isEmpty()&& sign==null){
            JOptionPane.showMessageDialog(null,"Fields are empty");
        }

        else if(field1.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null,"Fill out Id field");
        }
        else if(field2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Fill out Names");
        }
      
        else if(field4.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"address field is Required");
        }
        else if(field5.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"phone number field is Required");
        }
        
        else if(nid.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"NID field is Required");
        }
        
        else if(nid.getText().length()<16 || nid.getText().length()>16){
            JOptionPane.showMessageDialog(null,"NID  is 16 numbers");
        }
        
        else if( field5.getText().length()<10 || field5.getText().length()>10){
            JOptionPane.showMessageDialog(null,"Phone Number must have 10 numbers");
        }
        
        else if( !btn_female.isSelected()&& !btn_male.isSelected()){
            JOptionPane.showMessageDialog(null,"Select gender");
        }
        else if(field13.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"enter occupation");
        }
        else if(stmt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Enter statement to continue");
        }
        
         else if(sign == null){
            JOptionPane.showMessageDialog(null,"Add signature");
        }
        
        else{

           

            try{
                
            int id =Integer.parseInt(field1.getText());
            String names = field2.getText();
            String nd =nid.getText();
            String stm = stmt.getText();
            String address = field4.getText();
            String phone = field5.getText();
            String status="1";
            String occupation = field13.getText();
            Date d = new Date();
            SimpleDateFormat s =new SimpleDateFormat("d-MM-Y");
            String dates = s.format(d);
            
            File l = new File(path2);
            FileInputStream iss = new FileInputStream(l);
            String officer = "Officer X";
                
                Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                PreparedStatement st = Con.prepareStatement("INSERT INTO crime_reports VALUES(?,?,?,?,?,?,?,?,?,?,?,?)");

                st.setInt(1,id);
                st.setString(2,names);
                st.setString(3, nd);
                st.setString(4, gender);
                st.setString(5,address);
                st.setString(6, phone);
                st.setString(7,occupation);
                st.setString(8, stm);
                st.setBinaryStream(9, iss,(int) l.length());
                st.setString(10,dates);
                st.setString(11,status);
                st.setString(12,officer);

                st.executeUpdate();
                JOptionPane.showMessageDialog(null,"New Crime Report is Added ");
                field1.setText("");
                field2.setText("");
                stmt.setText("");
                nid.setText("");
                field4.setText("");
                field5.setText("");
                btn_female.setSelected(false);
                btn_male.setSelected(false);
                field13.setText("");
                sign.setIcon(null);
                field1.requestFocus();

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
            fetchData_Customer();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field2ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        Login info = new Login();
        info.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void docTblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docTblMouseReleased
        // TODO add your handling code here:
         int i = docTbl.getSelectedRow();
         if (i !=-1){
         if(search2.getText().isEmpty()){
         if(evt.getButton() == MouseEvent.BUTTON3){
         if(evt.isPopupTrigger() ){
         jPop.show(evt.getComponent(),evt.getX(),evt.getY());
        }
        }
         }
        
         }
       

    }//GEN-LAST:event_docTblMouseReleased

    private void search2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search2KeyReleased
        // TODO add your handling code here:

        DefaultTableModel table = (DefaultTableModel)docTbl.getModel();
        String search = search2.getText();
        TableRowSorter<DefaultTableModel>tr = new TableRowSorter<DefaultTableModel>(table);
        docTbl.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_search2KeyReleased

    
     
   private ImageIcon ResizeImg(String Imagepath){
       ImageIcon myimage = new ImageIcon(Imagepath);
       Image img = myimage.getImage();
       Image newimg = img.getScaledInstance(sign.getWidth(),sign.getHeight(),Image.SCALE_SMOOTH);
       ImageIcon image = new ImageIcon(newimg);
       return image;
    }
    private void signMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signMousePressed
        // TODO add your handling code here:
        
         JFileChooser j = new JFileChooser();
        j.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new  FileNameExtensionFilter("*.image","jpg","gif","png");
        j.addChoosableFileFilter(filter);
        int result = j.showSaveDialog(null);
        if(result== JFileChooser.APPROVE_OPTION){
            File selectedfile = j.getSelectedFile();
            path2 = selectedfile.getAbsolutePath();
            sign.setIcon(ResizeImg(path2));
        }
    }//GEN-LAST:event_signMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(no.getText().trim().isEmpty() && docowner.getText().trim().isEmpty() && docno.getText().trim().isEmpty() && docissue.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null,"Fields are empty");
        }

        else if(no.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null,"Fill out Serial no field");
        }
        else if(docowner.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Fill out Names");
        }
      
        else if(docno.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Number of document is Required");
        }
        else if(docissue.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Add place of issue");
        }
        
        
        
        else{

           

            try{
                
            int id =Integer.parseInt(no.getText());
            String names = docowner.getText();
            String docn =docno.getText();
            String pissue = docissue.getText();
            String doctyp = doctype.getSelectedItem().toString();
            String locatio = location.getSelectedItem().toString();
            Date d = new Date();
            SimpleDateFormat s =new SimpleDateFormat("d-MM-Y");
            String dates = s.format(d);
            String status = "Pending";
            String officer =  NewClass.emplnames;
                
                Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                PreparedStatement st = Con.prepareStatement("INSERT INTO documents VALUES(?,?,?,?,?,?,?,?,?)");

                st.setInt(1,id);
                st.setString(2,names);
                st.setString(3, doctyp);
                st.setString(4, docn);
                st.setString(5,pissue);
                st.setString(6, locatio);
                st.setString(7,officer);
                st.setString(8,dates);
                st.setString(9,status);
               

                st.executeUpdate();
                JOptionPane.showMessageDialog(null,"New Lost Document is Added ");
                no.setText("");
                docowner.setText("");
                docissue.setText("");
                docno.setText("");
                doctype.setSelectedIndex(0);
                location.setSelectedIndex(0);
                no.requestFocus();

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
            fetchData_Document();
            Police_Station();
            Documents_Type();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reportTblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportTblMouseReleased
        // TODO add your handling code here:
        
        
         int i = reportTbl.getSelectedRow();
         if (i !=-1){
         if(search3.getText().isEmpty()){
         if(evt.getButton() == MouseEvent.BUTTON3){
         if(evt.isPopupTrigger() ){
         popp.show(evt.getComponent(),evt.getX(),evt.getY());
        }
        }
         }
        
         }
         
    }//GEN-LAST:event_reportTblMouseReleased

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
        // TODO add your handling code here:
        
                
        int i = reportTbl.getSelectedRow();
        TableModel model = reportTbl.getModel();
        ReportDetails datum = new ReportDetails();
      
        datum.fname.setText(model.getValueAt(i,1).toString());
        datum.gender.setText(model.getValueAt(i,2).toString());
        datum.nid.setText(model.getValueAt(i,3).toString());
        datum.occupation.setText(model.getValueAt(i,4).toString());
        datum.phones.setText(model.getValueAt(i,5).toString());
        datum.address.setText(model.getValueAt(i,6).toString());
        datum.dates.setText(model.getValueAt(i,7).toString());
        
      
        
        String id= (model.getValueAt(i,0).toString());
         InputStream input;
         FileOutputStream output;

            try{
                Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                PreparedStatement m=Con.prepareStatement("SELECT * FROM crime_reports WHERE id=?");
                m.setString(1,id);

                ResultSet result =m.executeQuery();
                File theFile = new File(".jpg");
                output = new FileOutputStream(theFile);
                
                if(result.next()){
               
                   
                   String stm = result.getString("statement");
                   NewClass.names = stm;
                  
                   datum.st.setText(String.valueOf(NewClass.names).toString());
                   
                   String police_O= result.getString("officer");
                   NewClass.officer= police_O;
                   
                   datum.officers.setText(String.valueOf(NewClass.officer).toString());
                   
                   input = result.getBinaryStream("signature");
                   
                    byte[] buffer= new byte[1024];
                    while(input.read(buffer)>0){
                        output.write(buffer);
                    }
                    
                    
                    
                   String path = theFile.getAbsolutePath();
                  
                   ImageIcon myImage = new ImageIcon(path);
                   
                   Image img = myImage.getImage();
                   
                   Image newImg = img.getScaledInstance(datum.signature.getWidth(), datum.signature.getHeight(), Image.SCALE_SMOOTH);
                  
                   ImageIcon image = new ImageIcon(newImg);
                  
                   datum.signature.setIcon(image);
                   datum.setVisible(true);
                }

            }
            catch(Exception ex){
                ex.printStackTrace();
            }
    }//GEN-LAST:event_reportsActionPerformed

    private void editsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editsActionPerformed
        // TODO add your handling code here:
        
            
        int i = reportTbl.getSelectedRow();
        TableModel model = reportTbl.getModel();
        EditDetails datum = new EditDetails();
      
        datum.id.setText(model.getValueAt(i,0).toString());
        datum.fname.setText(model.getValueAt(i,1).toString());
        
        datum.nid.setText(model.getValueAt(i,3).toString());
        datum.occupation.setText(model.getValueAt(i,4).toString());
        datum.phones.setText(model.getValueAt(i,5).toString());
        datum.address.setText(model.getValueAt(i,6).toString());
        
         String sex = model.getValueAt(i,2).toString();
            if(sex.equals("F")){
                
                datum.btn_fe.setSelected(true);
                datum.btn_ma.setSelected(false);
            }
            else{
                datum.btn_ma.setSelected(true);
                datum.btn_fe.setSelected(false);
            }  
      
        
        String id= (model.getValueAt(i,0).toString());
         

            try{
                Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                PreparedStatement m=Con.prepareStatement("SELECT * FROM crime_reports WHERE id=?");
                m.setString(1,id);

                ResultSet result =m.executeQuery();
              
                if(result.next()){
               
                   
                   String stm = result.getString("statement");
                   NewClass.names = stm;
                  
                   datum.text.setText(String.valueOf(NewClass.names).toString());
                  
                   datum.setVisible(true);
                }

            }
            catch(Exception ex){
                ex.printStackTrace();
            }
    }//GEN-LAST:event_editsActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
        
               
        
    }//GEN-LAST:event_locationActionPerformed

    private void info2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info2MouseEntered
        // TODO add your handling code here:
        onHover2(info2);
    }//GEN-LAST:event_info2MouseEntered

    private void info2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info2MouseExited
        // TODO add your handling code here:
        onHoverLeave2(info2);
    }//GEN-LAST:event_info2MouseExited

    private void info2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info2MousePressed

       docType info = new docType();
       info.setVisible(true);

    }//GEN-LAST:event_info2MousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        messages info = new messages();
        info.setVisible(true);
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        onHover3(jPanel1);
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
        onHoverLeave3(jPanel1);
    }//GEN-LAST:event_jPanel1MouseExited

    private void statsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsActionPerformed
        // TODO add your handling code here:
        
      int i = docTbl.getSelectedRow();
         if (i !=-1){
             
              String id = docTbl.getValueAt(i,0).toString();
              String stat ="Collected";
              int option = JOptionPane.showConfirmDialog(null,"Do you really want to Change Status to Collected?","Status",JOptionPane.YES_NO_OPTION);
          
              if(option== 0){
        
              try{
              Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                PreparedStatement st = Con.prepareStatement("UPDATE documents SET status =? WHERE id=?");
                
                
                st.setString(1,stat);
                st.setString(2,id);
                st.execute();

              }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
           fetchData_Document();
        
              
         }
         
         }
        
        
    }//GEN-LAST:event_statsActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        
       int i = docTbl.getSelectedRow();
       TableModel model = docTbl.getModel();
       docDetails d = new docDetails();
       
       d.ref.setText(model.getValueAt(i,0).toString());
       d.fnames.setText(model.getValueAt(i,1).toString());
       d.dates.setText(model.getValueAt(i,2).toString());
       d.money.setText(model.getValueAt(i,3).toString());
       d.deposit.setText(model.getValueAt(i,4).toString());
       d.reso.setText(model.getValueAt(i,5).toString());
       d.balance.setText(model.getValueAt(i,6).toString());
      
       String id= (model.getValueAt(i,0).toString());
         

            try{
                Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                PreparedStatement m=Con.prepareStatement("SELECT * FROM documents WHERE id=?");
                m.setString(1,id);

                ResultSet result =m.executeQuery();
               
                if(result.next()){
               
                   String stm = result.getString("added_by");
                   NewClass.names = stm;
                  
                   d.server.setText(String.valueOf(NewClass.names).toString());
                   
                   String police_O= result.getString("Dates");
                   NewClass.officer= police_O;
                   
                   d.withdr.setText(String.valueOf(NewClass.officer).toString());
                   
                  
                   d.setVisible(true);
                }

            }
            catch(Exception ex){
                ex.printStackTrace();
            }
               
    }//GEN-LAST:event_viewActionPerformed

    private void field2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field2KeyTyped
        // TODO add your handling code here:
          field2.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {

         if(!(Character.isLetter(evt.getKeyChar()))){
                evt.consume();
            }
        }
    });
    }//GEN-LAST:event_field2KeyTyped

    private void field13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field13KeyTyped
        // TODO add your handling code here:
        field13.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {

         if(!(Character.isLetter(evt.getKeyChar()))){
                evt.consume();
            }
        }
    });
    }//GEN-LAST:event_field13KeyTyped

    private void nidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nidKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_nidKeyTyped

    private void field5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field5KeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_field5KeyTyped

    private void docnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_docnoKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_docnoKeyTyped

    private void docownerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_docownerKeyTyped
        // TODO add your handling code here:
        docowner.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {

         if(!(Character.isLetter(evt.getKeyChar()))){
                evt.consume();
            }
        }
    });
    }//GEN-LAST:event_docownerKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        case_results info = new case_results();
        info.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed
 
    
   public void fetchData_Customer() {
        
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                
                Statement st = Con.createStatement();
                ResultSet rs = st.executeQuery("SELECT id,Names,gender,nid,Occupation,phone,address,date FROM crime_reports");
                while(reportTbl.getRowCount() > 0 ){
                    ((DefaultTableModel)reportTbl.getModel()).removeRow(0);
                    
                   
                    
                }
                
                 int col = rs.getMetaData().getColumnCount();
                 while(rs.next()){
                     Object [] rows = new Object[col];
                     for(int l = 1; l <= col; l++ )
                     {
                        rows[l-1] = rs.getObject(l);
                     }
                     ((DefaultTableModel)reportTbl.getModel()).insertRow(rs.getRow() -1, rows);
                     
                 }
                rs.close();
                st.close();
                
            } 
            catch (Exception e) {
                e.printStackTrace();
            }
            
        
    }
   
   public void fetchData_Document() {
        
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                
                Statement st = Con.createStatement();
                ResultSet rs = st.executeQuery("SELECT id,names,doc_type,doc_number,place_issue,police_station,status FROM documents");
                while(docTbl.getRowCount() > 0 ){
                    ((DefaultTableModel)docTbl.getModel()).removeRow(0);
                    
                   
                    
                }
                
                 int col = rs.getMetaData().getColumnCount();
                 while(rs.next()){
                     Object [] rows = new Object[col];
                     for(int l = 1; l <= col; l++ )
                     {
                        rows[l-1] = rs.getObject(l);
                     }
                     ((DefaultTableModel)docTbl.getModel()).insertRow(rs.getRow() -1, rows);
                     
                 }
                rs.close();
                st.close();
                
            } 
            catch (Exception e) {
                e.printStackTrace();
            }
            
        
    }
   
    public void fetch_Doc_types(){
       
        try{
                Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                
                PreparedStatement st = Con.prepareStatement("SELECT * FROM doc_types");

                 st.execute();
               
        }
          catch(Exception e){
                   e.printStackTrace();
                  }
   }
   
   public void generateId(){
       
        try{
                Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                
                PreparedStatement st = Con.prepareStatement("SELECT COUNT(id)+1 FROM crime_reports");

                 ResultSet rs = st.executeQuery();
                if(rs.next()){
                  int Id = rs.getInt(1);
                  NewClass.Id = Id; 
                  field1.setText(String.valueOf(NewClass.Id).toString());
                }
               
                
        }
          catch(Exception e){
                   e.printStackTrace();
                  }
   }
   
   public void generateDocId(){
       
        try{
                Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                
                PreparedStatement st = Con.prepareStatement("SELECT COUNT(id)+1 FROM documents");

                 ResultSet rs = st.executeQuery();
                if(rs.next()){
                  int Id = rs.getInt(1);
                  NewClass.Id = Id; 
                  no.setText(String.valueOf(NewClass.Id).toString());
                }
               
                
        }
          catch(Exception e){
                   e.printStackTrace();
                  }
   }
   
   void Police_Station(){
       
        try{
           Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
            PreparedStatement m=Con.prepareStatement("SELECT station_name FROM station");
            
            ResultSet result =m.executeQuery();
            while(result.next()){
                
                  
                  String station = result.getString("station_name");
                  NewClass.name = station; 
                  
                  location.addItem(result.getString("station_name"));
                  
                  
                             }
            
        }
        catch(Exception ex){
           ex.printStackTrace();
        }
                                   
   }
   
   
   void Documents_Type(){
       
        try{
           Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
            PreparedStatement m=Con.prepareStatement("SELECT * FROM doc_types");
            
            ResultSet result =m.executeQuery();
            while(result.next()){
                
                  
                  String docs = result.getString("document_type");
                  NewClass.doc = docs; 
                  
                  doctype.addItem(result.getString("document_type"));
                  
                  
                             }
            
        }
        catch(Exception ex){
           ex.printStackTrace();
        }
                                   
   }
   
   
    void onHover2(JPanel panel){
        panel.setBackground(new Color(60,144,139));
        
    }
       
         void onHoverLeave2(JPanel panel){
        panel.setBackground(new Color(115,167,179));
        
    }
         
    void onHover3(JPanel panel){
        panel.setBackground(new Color(115,167,179));
        
    }
       
    void onHoverLeave3(JPanel panel){
    panel.setBackground(new Color(243,243,252));
        
    }
   
   
    
    void setcolor(JPanel panel){
        panel.setBackground(new Color(115,167,179));
        
    }
    
     void resetcolor(JPanel panel){
        panel.setBackground(new Color(64,112,130));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managerPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg2;
    private javax.swing.JPanel btn_check;
    private javax.swing.JPanel btn_create;
    private javax.swing.JPanel btn_edit;
    private javax.swing.JRadioButton btn_female;
    private javax.swing.JPanel btn_home;
    private javax.swing.JRadioButton btn_male;
    private javax.swing.JPanel check;
    private javax.swing.JPanel create;
    private javax.swing.JTable docTbl;
    private javax.swing.JTextField docissue;
    private javax.swing.JTextField docno;
    private javax.swing.JTextField docowner;
    private javax.swing.JComboBox<String> doctype;
    public javax.swing.JPanel edit;
    private javax.swing.JMenuItem edits;
    private javax.swing.JLabel employeeName;
    private javax.swing.JTextField field1;
    private javax.swing.JTextField field13;
    private javax.swing.JTextField field2;
    private javax.swing.JTextField field4;
    private javax.swing.JTextField field5;
    public javax.swing.JPanel home;
    private javax.swing.JPanel info2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> location;
    public javax.swing.JPanel main;
    private javax.swing.JTextField nid;
    private javax.swing.JTextField no;
    private javax.swing.JPopupMenu popp;
    private javax.swing.JTable reportTbl;
    private javax.swing.JMenuItem reports;
    private javax.swing.JLabel reveal;
    private javax.swing.JTextField search2;
    private javax.swing.JTextField search3;
    private javax.swing.JLabel sign;
    private javax.swing.JMenuItem stats;
    private javax.swing.JTextArea stmt;
    private javax.swing.JLabel time;
    private javax.swing.JPanel top;
    private javax.swing.JMenuItem view;
    // End of variables declaration//GEN-END:variables
    private String gender;
    private String path;
    private String path2;
    
   
    
    private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_Filled_Bookmark_Ribbon_60px_1.png")));
    }
}
