
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muvunyi
 */
public class NewStation extends javax.swing.JFrame {

    /**
     * Creates new form NewStation
     */
    public NewStation() {
        initComponents();
        fetchData_Station(); 
        seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPop = new javax.swing.JPopupMenu();
        delete = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        srno = new javax.swing.JTextField();
        station = new javax.swing.JTextField();
        jButtonx = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stationTbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonx1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete Station");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPop.add(delete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(180, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.setForeground(new java.awt.Color(149, 175, 192));

        jButtonx.setBackground(new java.awt.Color(68, 128, 112));
        jButtonx.setForeground(new java.awt.Color(255, 255, 255));
        jButtonx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Enter_17px_1.png"))); // NOI18N
        jButtonx.setText("ADD");
        jButtonx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxActionPerformed(evt);
            }
        });

        stationTbl.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        stationTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No", "Station Name", "Created On"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stationTbl.setGridColor(new java.awt.Color(255, 255, 255));
        stationTbl.setRowHeight(35);
        stationTbl.setSelectionBackground(new java.awt.Color(68, 132, 121));
        stationTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                stationTblMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(stationTbl);
        if (stationTbl.getColumnModel().getColumnCount() > 0) {
            stationTbl.getColumnModel().getColumn(0).setResizable(false);
            stationTbl.getColumnModel().getColumn(0).setPreferredWidth(8);
            stationTbl.getColumnModel().getColumn(1).setResizable(false);
            stationTbl.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel2.setText("Serial Number");

        jLabel3.setText("Station Name");

        jButtonx1.setForeground(new java.awt.Color(0, 51, 51));
        jButtonx1.setText("BACK");
        jButtonx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonx1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(station, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(srno)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonx1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(srno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(station, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonx, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonx1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jPanel2.setBackground(new java.awt.Color(68, 132, 121));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("POLICE STATIONS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(102, 102, 102))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxActionPerformed
        // TODO add your handling code here:
      
        if(srno.getText().trim().isEmpty() && station.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null,"Fields are empty");
        }

        else if(srno.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null,"add station serial number");
        }
        else if(station.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Fill out Station Name");
        }
        
        

        else{

            int id =Integer.parseInt(srno.getText());
            String names = station.getText();
            Date d = new Date();
            SimpleDateFormat s =new SimpleDateFormat("d-MM-Y");
            String dates = s.format(d);

            try{
                Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                PreparedStatement st = Con.prepareStatement("INSERT INTO station VALUES(?,?,?)");

                st.setInt(1,id);
                st.setString(2,names);
                st.setString(3,dates);
                

                st.execute();

                JOptionPane.showMessageDialog(null,"New Station Added");
                srno.setText("");
                station.setText("");
                srno.requestFocus();

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }

        }
        fetchData_Station();
    }//GEN-LAST:event_jButtonxActionPerformed

    private void jButtonx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonx1ActionPerformed
        // TODO add your handling code here:  
        setVisible(false);
        AdminPanel info = new AdminPanel();
        info.setVisible(true);
                               
    }//GEN-LAST:event_jButtonx1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        
         int i = stationTbl.getSelectedRow();
         if (i !=-1){
             
              String id = stationTbl.getValueAt(i,0).toString();
              int option = JOptionPane.showConfirmDialog(null,"Do you really want to delete?","Station",JOptionPane.YES_NO_OPTION);
          
              if(option== 0){
        
              try{
              Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                PreparedStatement st = Con.prepareStatement("DELETE FROM station WHERE id=?");

                st.setString(1,id);
                st.execute();

              }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
            fetchData_Station();
        
              
         }
         
         }
    }//GEN-LAST:event_deleteActionPerformed

    private void stationTblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stationTblMouseReleased
        // TODO add your handling code here:
          int i = stationTbl.getSelectedRow();
         if (i !=-1){
        
         if(evt.getButton() == MouseEvent.BUTTON3){
         if(evt.isPopupTrigger() ){
         jPop.show(evt.getComponent(),evt.getX(),evt.getY());
        }
        }
        
        
         }
    }//GEN-LAST:event_stationTblMouseReleased

    
    
     void fetchData_Station() {
        
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection Con=DriverManager.getConnection("jdbc:mysql://localhost/police","root","");
                
                Statement st = Con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM station");
                while(stationTbl.getRowCount() > 0){
                    ((DefaultTableModel)stationTbl.getModel()).removeRow(0);
                   
                    
                }
                
                 int col = rs.getMetaData().getColumnCount();
                 while(rs.next()){
                     Object [] rows = new Object[col];
                     for(int l = 1; l <= col; l++ )
                     {
                        rows[l-1] = rs.getObject(l);
                     }
                     ((DefaultTableModel)stationTbl.getModel()).insertRow(rs.getRow() -1, rows);
                 }
                rs.close();
                st.close();
                
            } 
            catch (Exception e) {
                e.printStackTrace();
            }
       
    }
     
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem delete;
    private javax.swing.JButton jButtonx;
    private javax.swing.JButton jButtonx1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPop;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField srno;
    public javax.swing.JTextField station;
    private javax.swing.JTable stationTbl;
    // End of variables declaration//GEN-END:variables
 private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_Filled_Bookmark_Ribbon_60px_1.png")));
    }
}
